name: Docker Build

on:
  push:
    branches:
      - main
    paths:
      - ./cloud/lab3/pushhere/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t my-docker-image ./cloud/lab3

    - name: Save hello.txt
      run: |
        docker run --rm -v $(pwd):/output my-docker-image cp /hello.txt /output/hello.txt

    - name: Upload hello.txt
      uses: actions/upload-artifact@v2
      with:
        name: hello-text-file
        path: hello.txt
